config/routes.rb
Rails.application.routes.draw do
  
  root 'staticpages#home'
  # get 'staticpages/home'
  get '/help', to: 'staticpages#help'
  get '/about', to: 'staticpages#about'
  get '/contact', to: 'staticpages#contact'
  get 'signup', to: 'users#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
    def full_title (title)
        if title.empty?
            "Microposts"
        else
            title
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title><%= full_title(yield(:title)) %></title>
      <meta charset="utf-8">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/partial/shim' %>
  </head>
  <body>
      <%= render 'layouts/partial/header' %>
  <div class="container">
      <%= yield %>
  </div>
  <%= render 'layouts/partial/footer' %>
</body>
</html>

app/views/layouts/partial/_footer.html.erb
<footer class="footer">
    <small>
            The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="https://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/partial/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/partial/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/staticpages/about.html.erb
<%= provide(:title,"About")%>
<title><%= yield(:title) %></title>
<h1><%= yield(:title) %> Details</h1>

app/views/staticpages/contact.html.erb
<%= provide(:title,"Contact")%>
<title><%= yield(:title) %></title>
<h1><%= yield(:title) %> Details</h1>

app/views/staticpages/help.html.erb
<%= provide(:title,"Help")%>
<title><%= yield(:title) %></title>
<h1><%= yield(:title) %> Details</h1>

app/views/staticpages/home.html.erb
<div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>
    <h2> This is the home page for the
        <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        sample application.
        </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("", alt: "Rails logo", width: "200"), "https://rubyonrails.org/" %>

app/views/users/new.html.erb
<%= provide(:title,"Signup")%>
<title><%= yield(:title) %></title>
<h1><%= yield(:title) %> Details</h1>